# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: render-html

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: yarn build:css-processor
      name: Build dependencies (css-processor)
    - run: yarn build:transient-render-engine
      name: Build dependencies (transient-render-engine)
    - run: yarn test:render-html:ts
      name: Typescript Tests
    - run: yarn run test:render-html:lint
      name: Linting Tests
    - run: yarn run test:render-html:jest --coverage
      name: Behavior Tests
    - run: yarn build:render-html
      name: Build
    - uses: codecov/codecov-action@v4
      with:
        flags: render-html
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
